spring.application.name=tallerElectiva

spring.datasource.url=jdbc:mysql://localhost:3306/midb
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update




server.port=9000

