spring.application.name=con_base_dedatos
# Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/taller_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=9000
