spring.application.name=security-inicio
server.port=${SERVER_PORT:9090}

spring.security.user.name=${SECURITY_USER:Johan}
spring.security.user.password=${SECURITY_PASSWORD:Password123}

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}